<?php
	add_filter( 'elementor/icons_manager/additional_tabs', 'gicon_custom_icons_filters' , 9999999, 1 );
	function gicon_custom_icons_filters( $tabs = array() ) {
		$newicons = [
			'dicon-handshake',
			'dicon-thumbs-up',
			'dicon-stethoscope-1',
			'dicon-share',
			'dicon-contact',
			'dicon-location-1',
			'dicon-crowdfunding',
			'dicon-pin-1',
			'dicon-chat',
			'dicon-pin-2',
			'dicon-translation',
			'dicon-chat-1',
			'dicon-entrepreneur',
			'dicon-crowdfunding-1',
			'dicon-creativity',
			'dicon-graphic-designer',
			'dicon-mission-1',
			'dicon-photograph',
			'dicon-checked',
			'dicon-skincare',
			'dicon-minus',
			'dicon-mission',
			'dicon-team',
			'dicon-team-1',
			'dicon-cancer',
			'dicon-charity',
			'dicon-family',
			'dicon-hamburger',
			'dicon-health',
			'dicon-heart',
			'dicon-mortarboard',
			'dicon-peace-1',
			'dicon-peace',
			'dicon-pet',
			'dicon-praying',
			'dicon-stethoscope',
			'dicon-target',
			'dicon-water-bottle',
			'dicon-phone-call',
			'dicon-chat-2',
			'dicon-donation-1',
			'dicon-adoption',
			'dicon-support',
			'dicon-message',
			'dicon-right-arrow-2',
			'dicon-exploration',
			'dicon-college-graduation',
			'dicon-charity-2',
			'dicon-checked-2',
			'dicon-message-1',
			'dicon-selection',
			'dicon-fundraiser',
			'dicon-delete',
			'dicon-maternity',
			'dicon-quote',
			'dicon-clipboard',
			'dicon-right-arrow-1',
			'dicon-cheque',
			'dicon-coin',
			'dicon-water',
			'dicon-left-arrow-1',
			'dicon-heart-2',
			'dicon-heart-1',
			'dicon-fast-food',
			'dicon-phone-2',
			'dicon-handshake-2',
			'dicon-address',
			'dicon-left-arrow-2',
			'dicon-shopping-cart',
			'dicon-charity-1',
			'dicon-focus',
			'dicon-magnifying-glass',
			'dicon-donation',
			'dicon-check',
			'dicon-dove',
			'dicon-graduation',
			'dicon-health-check',
			'dicon-star',
			'dicon-email',
			'dicon-shopping-cart-2',
			'dicon-search-interface-symbol',
			'dicon-down',
			'dicon-right',
			'dicon-play-button-arrowhead',
			'dicon-volunteering',
			'dicon-apartment',
			'dicon-world',
			'dicon-insurance-agent',
			'dicon-quotes',
			'dicon-tag',
			'dicon-bubble-chat',
			'dicon-maps-and-flags',
			'dicon-email-2',
			'dicon-telephone-call',
			'dicon-email-1',
			'dicon-calendar',
			'dicon-facebook-app-symbol',
			'dicon-twitter',
			'dicon-linkedin',
			'dicon-youtube',
			'dicon-up-arrow',
			'dicon-user',
			'dicon-solidarity',
			'dicon-donation-2',
			'dicon-clock',
			'dicon-share',
			'dicon-straight-quotes',
			'dicon-teamwork',
			'dicon-call',
			'dicon-healthy-food',
			'dicon-rating',
			'dicon-checked-3',
			'dicon-menu',
			'dicon-camera',
			'dicon-movie',
			'dicon-warning',
			'dicon-star-1',
			'dicon-check-2',
			'dicon-plus',
			'dicon-placeholder',
			'dicon-email-3',
			'dicon-hide'
		];

		$icons['gva_custom_icon'] = array(
			  'name'          => 'dicon-icons-theme',
			  'label'         => esc_html__( 'Icons Theme', 'donatm-themer' ),
			  'labelIcon'     => 'fas fa-user',
			  'prefix'        => '',
			  'displayPrefix' => '',
			  'icons'         => $newicons,
			  'url'          => GAVIAS_DONATM_PLUGIN_URL . 'assets/icons/style.css',
			  'ver'           => '1.0',
		 );

		return array_merge( $tabs, $icons );
	}

	add_action( 'wp_print_footer_scripts', 'gicon_insert_icons_footer_css'  );
	function gicon_insert_icons_footer_css() {
		echo '<link rel="stylesheet" type="text/css" href="' . GAVIAS_DONATM_PLUGIN_URL . 'assets/icons/style.css">';
	}
