apiVersion: apps/v1
kind: Deployment
metadata:
  name: sanyachildrenshome
  labels:
    app: sanyachildrenshome
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sanyachildrenshome
  template:
    metadata:
      labels:
        app: sanyachildrenshome
    spec:
      securityContext:
        fsGroup: 33  # www-data group ID
        fsGroupChangePolicy: "Always"
      initContainers:
        - name: fix-permissions
          image: busybox:1.35
          command: ['sh', '-c']
          args:
            - |
              echo "Setting up WordPress file permissions..."
              chown -R 33:33 /var/www/html/wp-content
              find /var/www/html/wp-content -type d -exec chmod 755 {} \;
              find /var/www/html/wp-content -type f -exec chmod 644 {} \;
              chmod 755 /var/www/html/wp-content/uploads
              echo "Permissions set successfully"
          volumeMounts:
          - name: sanyachildrenshome-volume
            mountPath: "/var/www/html/wp-content"
          securityContext:
            runAsUser: 0  # Run as root to change ownership
      containers:
        - name: sanyachildrenshome
          image: registry.gitlab.com/__DOCKER_REPOSITORY__/__IMAGE_NAME__:__IMAGE_TAG__
          imagePullPolicy: Always
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: false
          # resources:
          #   requests:
          #     cpu: "20m"        # Baseline CPU request
          #     memory: "300Mi"    # Baseline memory request
          #   limits:
          #     cpu: "100m"        # Max CPU limit (4x request)
          #     memory: "400Mi"    # Max memory limit (2x request)
          volumeMounts:
          - name: sanyachildrenshome-volume
            mountPath: "/var/www/html/wp-content"      
      volumes:
        - name: sanyachildrenshome-volume
          persistentVolumeClaim:
            claimName: sanyachildrenshome-pvc
      imagePullSecrets:
        - name: regcred