name: Sanya Childrens Home CI/CD workflow

on:
  push:
    branches: [ "main" ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    env:
      DOCKER_REPOSITORY: bensonokiora
      IMAGE_NAME: sanyachildrenshome_docker
      IMAGE_TAG: release${{ github.run_number }}

    steps:
      - name: Install doctl
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}

      - uses: actions/checkout@v3


      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to GitLab Container Registry
        uses: docker/login-action@v2
        with:
          registry: registry.gitlab.com
          username: ${{ secrets.GITLAB_USERNAME }}
          password: ${{ secrets.GITLAB_PASSWORD }}

      - name: Build and push API image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: registry.gitlab.com/${{ env.DOCKER_REPOSITORY }}/${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}
          

      - name: Replace tokens in deployment files
        uses: cschleiden/replace-tokens@v1
        with:
          files: '["kubernetes/*.yaml"]'
          tokenPrefix: '__'
          tokenSuffix: '__'
        env:
          DOCKER_REPOSITORY: ${{ env.DOCKER_REPOSITORY }}
          IMAGE_NAME: ${{ env.IMAGE_NAME }}
          IMAGE_TAG: ${{ env.IMAGE_TAG }}

      - name: deploy to k8s
        uses: Azure/k8s-set-context@v3.0
        with:
          kubeconfig: ${{ secrets.KUBE_CONFIG }}

      - name: Kubectl tool installer
        uses: Azure/setup-kubectl@v3

      - name: Deploy to Kubernetes cluster
        uses: Azure/k8s-deploy@v4
        with:
          namespace: 'default'
          manifests: |
              kubernetes/deployment.yaml
